# 贝叶斯计算 {#chap:bayesian-computation}

> 参考课程资料 <https://github.com/florianhartig/LearningBayes>


从 WinBUGS\index{WinBUGS} 到 OpenBUGS\index{OpenBUGS}，从 JAGS\index{JAGS} 到 Stan\index{Stan}，BUGS 的发展从未停止过，Stan <https://mc-stan.org/> 是一个统计建模和高性能统计计算平台。可用于贝叶斯框架下，空间广义线性混合效应模型的参数估计基于 GPU 加速是一个不错的选择， Stan 开发者也把 GPU 加速列入开发日程。SCIKIT-CUDA 和 ArrayFire 等基于 CUDA 开发的通用加速框架获得越来越多的关注。基于 Stan 实现的汉密尔顿蒙特卡罗算法
不管怎么改进 MCMC 算法，它始终是一个计算量非常大，非常耗时的算法，那么高效地实现就比较有意义，基于 C++ 语言编写的高性能计算库 Stan，其主要目的是实现

1. 全贝叶斯推断使用 No-U-Turn 采样器，是汉密尔顿蒙特卡罗算法的变种
1. 近似贝叶斯推断使用自动微分变分推理方法
1. 惩罚极大似然估计使用 L-BFGS 优化算法

四个重点
:   数值微分比自动微分糟糕；优化比MCMC采样糟糕；用于可微的后验分布采样算法中， Gibbs采样特别是 Metropolis-Hasting 采样比 NUTS 采样糟糕；容易地创建一个R 包去使用Stan 实现的 NUTS 算法

什么是 Stan
:   Stan 是一门新的表示统计模型的编程语言，包含一个从高级的Stan语法到低级的 C++ 语法的翻译器，包含支持自动微分的矩阵和标量计算的数学库，包含用于统计推断的新的基于梯度的算法，包含R、Python 等多种高级语言的接口，包含后验估计的R函数，包含大量社区用户和开发者。 Ben Goodrich 在 [2017年国际 R 语言大会](https://www.youtube.com/watch?v=Q2bG_EqVQPQ) 上介绍如何使用 RStan 估计统计模型参数

谁在使用 Stan
:   Stan 正被学术、商业和政府部门的人使用，至写作时间已有62个R包依赖 rstan 包，特别是 rstan/rstanarm/brms/prophet 下载量都比较大，Stan 可以用来拟合气候模型，临床药物，基因和癌症生物，种群动态，心理学和社会网络，推荐系统等

## 贝叶斯定理 {#Bayes-Theorem}

根据条件概率定义、链式法则、全概率公式，有

\begin{align}
\begin{array}{rcll}
p(\boldsymbol{\theta}|\mathbf{Y})  & =  & \displaystyle \frac{p(\boldsymbol{\theta},\mathbf{Y})}{p(\mathbf{Y})}
& \mbox{ [条件概率定义]}
\\
& = & \displaystyle \frac{p(\mathbf{Y}|\boldsymbol{\theta}) p(\boldsymbol{\theta})}{p(\mathbf{Y})}
& \mbox{ [链式法则]}
\\
& = & \displaystyle \frac{p(\mathbf{Y}|\boldsymbol{\theta})p(\boldsymbol{\theta})}{\int_{\Theta}p(\mathbf{Y},\boldsymbol{\theta})d\boldsymbol{\theta}}
& \mbox{ [全概率公式]}
\\
& = & \displaystyle \frac{p(\mathbf{Y}|\boldsymbol{\theta})p(\boldsymbol{\theta})}{\int_{\Theta}p(\mathbf{Y}|\boldsymbol{\theta})p(\boldsymbol{\theta})d\boldsymbol{\theta}}
& \mbox{ [链式法则]}
\\
& \propto & \displaystyle p(\mathbf{Y}|\boldsymbol{\theta})p(\boldsymbol{\theta})
& \mbox{ [$\mathbf{Y}$ 已知]}
\end{array} (\#eq:bayes-theorem)
\end{align}
