# 数据搬运 {#chap:data-transportation}




## 数据库与 R 语言 {#sec:database}

[SQLite](https://www.sqlite.org/) 数据库

```bash
sudo dnf install sqlite sqlite-devel
```


驱动配置文件 odbcinst.ini

```
[SQLite Driver]
Driver          = /usr/local/lib/libsqlite3odbc.dylib
```

连接配置文件 odbc.ini

```
[SQLite]
Driver          = SQLite Driver
Database        = /tmp/testing
```



仅介绍 RSQLite 和  odbc 两个 R 包，其余数据库与 R 连接和使用的方式类似，详见文章 --- [从 R 连接 MySQL](https://cosx.org/2020/06/connect-mysql-from-r/)

MySQL 为例介绍 odbc 的连接和使用，特别是事务操作

```{sql,eval=F}
-- !preview conn=DBI::dbConnect(odbc::odbc(),  driver = "MariaDB", database = "demo", uid = "root", pwd = "cloud", host = "localhost", port = 3306)

SELECT * FROM mtcars
LIMIT 10
```

我的系统已经安装了多款数据库的 ODBC 驱动

```bash
dnf install -y unixODBC unixODBC-devel mariadb-connector-odbc postgresql-odbc
```

```r
odbc::odbcListDrivers()
```
```
         name   attribute                       value
1  PostgreSQL Description         ODBC for PostgreSQL
2  PostgreSQL      Driver       /usr/lib/psqlodbcw.so
3  PostgreSQL       Setup    /usr/lib/libodbcpsqlS.so
4  PostgreSQL    Driver64     /usr/lib64/psqlodbcw.so
5  PostgreSQL     Setup64  /usr/lib64/libodbcpsqlS.so
6  PostgreSQL   FileUsage                           1
7       MySQL Description              ODBC for MySQL
8       MySQL      Driver      /usr/lib/libmyodbc5.so
9       MySQL       Setup      /usr/lib/libodbcmyS.so
10      MySQL    Driver64    /usr/lib64/libmyodbc5.so
11      MySQL     Setup64    /usr/lib64/libodbcmyS.so
12      MySQL   FileUsage                           1
13    FreeTDS Description Free Sybase & MS SQL Driver
14    FreeTDS      Driver      /usr/lib/libtdsodbc.so
15    FreeTDS       Setup         /usr/lib/libtdsS.so
16    FreeTDS    Driver64    /usr/lib64/libtdsodbc.so
17    FreeTDS     Setup64       /usr/lib64/libtdsS.so
18    FreeTDS        Port                        1433
19    MariaDB Description            ODBC for MariaDB
20    MariaDB      Driver       /usr/lib/libmaodbc.so
21    MariaDB    Driver64     /usr/lib64/libmaodbc.so
22    MariaDB   FileUsage                           1
```



## 批量读取 csv 文件

iris 拆分成 csv xlsx 文件，分别用 fread/openxlsx 批量读取、导出

按照 Species 分组拆成单独的 csv 文件，各个文件的文件名用鸢尾花的类别名表示

```{r,eval=FALSE}
# 批量分组导出
library(data.table)
as.data.table(iris)[, fwrite(.SD, paste0("data/user_", unique(Species), ".csv")), by = Species, .SDcols = colnames(iris)]
```


```{r,eval=FALSE}
library(data.table)

merged_df <- do.call('rbind', lapply(list.files(pattern = "*.csv", path = "data/"), fread ) )
```


```{r,eval=FALSE}
xdf$date <- as.Date(xdf$date)
xdf$ts <- as.POSIXct(as.numeric(xdf$ts), origin = "1978-01-01")
split(xdf[order(xdf$ts), ], interaction(xdf$study, xdf$port)) %>%
  lapply(function(.x) {
    .x[nrow(.x), ]
  }) %>%
  unname() %>%
  Filter(function(.x) {
    nrow(.x) > 0
  }, .) %>%
  do.call(rbind.data.frame, .)

library(dplyr)
xdf %>%
  mutate(
    date = as.Date(date),
    ts = anytime::anytime(as.numeric(ts))
  ) %>%
  arrange(ts) %>%
  group_by(study, port) %>%
  slice(n()) %>%
  ungroup()
```


```{r}
library(tibble)
library(magrittr)

mtcars <- tibble(mtcars)

mtcars %>% 
  print(n = 16, width = 69)
```


```{r}
mtcars %>% 
  print(., n = nrow(.)/4)
```

## 批量导出 xlsx 文件


将 R 环境中的数据集导出为 xlsx 表格

```{r,eval=FALSE}
## 加载 openxlsx 包
library(openxlsx)
## 创建空白的工作薄，标题为鸢尾花数据集
wb <- createWorkbook(title = "鸢尾花数据集")
## 添加 sheet 页
addWorksheet(wb, sheetName = "iris")
# 将数据写进 sheet 页
writeData(wb, sheet = "iris", x = iris, colNames = TRUE)
# 导出数据到本地
saveWorkbook(wb, file = "iris.xlsx", overwrite = TRUE)
```

