# 深度学习 {#chap-deep-learning}

- 递归神经网络
- 卷积神经网络
- 记忆神经网络

深度学习计算框架 [PyTorch](http://pytorch.org/)  [Caffe2](https://caffe2.ai/)

Local Interpretable Model-Agnostic Explanations (R port of original Python package) [lime](https://github.com/thomasp85/lime)

Explanations of model predictions with live and breakDown packages <https://arxiv.org/abs/1804.01955>

Descriptive mAchine Learning EXplanations [DALEX](https://github.com/pbiecek/DALEX)

deep learning from first principles in python r and octave <https://gigadom.wordpress.com>

[fastai](https://github.com/EagerAI/fastai)

## mxnet

[mxnet](https://github.com/apache/incubator-mxnet) 提供了 R 包 <https://github.com/apache/incubator-mxnet/tree/master/R-package>

Lightweight, Portable, Flexible Distributed/Mobile Deep Learning with Dynamic, Mutation-aware Dataflow Dep Scheduler; for Python, R, Julia, Scala, Go, Javascript and more

```r
cran <- getOption("repos")
cran["dmlc"] <- "https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/R/CRAN/"
options(repos = cran)
install.packages("mxnet")
```

## tensorflow

[Deep learning at rstudio::conf 2018](https://rviews.rstudio.com/2018/02/14/deep-learning-rstudio-conf-2018/) 深度学习与R语言,J.J.作为 RStudio 的 CEO 推动 tensorflow 在 R 中的使用，两个幻灯片值得好好看，J.J. 介绍 tensorflow Javier Luraschi介绍tf的部署

- [Yann LeCun](http://yann.lecun.com/)
- [Yoshua Bengio](http://www.iro.umontreal.ca/~bengioy/yoshua_en/index.html)
- [Ian Goodfellow](http://www.iangoodfellow.com/)

[TensorFlow 资源列表：书籍，材料列表](https://hackerlists.com/tensorflow-resources/)

Computation using data flow graphs for scalable machine learning. TensorFlow is an open source software library for numerical computation using data flow graphs.

RStudio 公司为 [tensorflow](https://github.com/tensorflow/tensorflow) 开发了 R 包接口 [tensorflow](https://github.com/rstudio/tensorflow) 和 [keras](https://github.com/rstudio/keras)

Gaussian processes in TensorFlow <https://github.com/GPflow/GPflow>
文档 <http://gpflow.readthedocs.io/en/latest/> 提到了 Fully Bayesian inference for generalized GP models with HMC 可以考虑与 Stan 比较性能

相关的框架 [Trieste](https://github.com/secondmind-labs/trieste) 主要在于贝叶斯框架下的优化计算，相关使用文档见 <https://gpflowopt.readthedocs.io/en/latest>
