# 梯度提升机 {#chap:gradient-boosting-machine}

> [梯度提升相关的论文合集](https://github.com/benedekrozemberczki/awesome-gradient-boosting-papers) Jerome H. Friedman 的论文 [Greedy function approximation: A gradient boosting machine](https://projecteuclid.org/euclid.aos/1013203451)

基于树的梯度提升算法，在分类和回归任务上的表现，介绍基本算法内容后，比较实现方式和效率，寻求最佳工程实战

gbm h2o caret xgboost catboost lightgbm [compboost](https://github.com/schalkdaniel/compboost)

二分类问题的开源实现比较 <https://github.com/szilard/benchm-ml>

GBM 算法各种实现的性能比较 <https://github.com/szilard/GBM-perf>

[useR! 2018 Machine Learning Tutorial](https://koalaverse.github.io/machine-learning-in-R/)


## gbm

[gbm](https://github.com/gbm-developers/gbm) 已经退休了，目前由 [gbm3](https://github.com/gbm-developers/gbm3) 继任

## h2o

参考学习和培训材料 [h2o-tutorials](https://github.com/h2oai/h2o-tutorials)

## caret
## xgboost

开发仓库 <https://github.com/dmlc/xgboost>
XGBoost is an optimized distributed gradient boosting library designed to be highly efficient, flexible and portable. It implements machine learning algorithms under the Gradient Boosting framework. XGBoost provides a parallel tree boosting (also known as GBDT, GBM) that solve many data science problems in a fast and accurate way. The same code runs on major distributed environment (Hadoop, SGE, MPI) and can solve problems beyond billions of examples.

使用文档 <http://xgboost.readthedocs.io/en/latest/>
R 包 <https://github.com/dmlc/xgboost/tree/master/R-package>
中文文档 <http://xgboost.apachecn.org/cn/latest/>


## catboost

[catboost](https://github.com/catboost/catboost)

```r
remotes::install_github('catboost/catboost', subdir = 'catboost/R-package')
```

CatBoost is an open-source gradient boosting on decision trees library with categorical features support out of the box for Python, R https://catboost.ai


```r
# windows 
devtools::install_url('https://github.com/catboost/catboost/releases/download/v0.6.1.1/catboost-R-Windows-0.6.1.1.tgz', args = c("--no-multiarch"))
# Ubuntu install libc6-dev first
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
```


[xLearn](https://github.com/aksnzhy/xlearn)


## LightGBM


[LightGBM](https://github.com/Microsoft/LightGBM/tree/master/R-package) A fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.

提供了 R 包，微软的工具主要支持 Windows 平台和 VS 编译工具。顺便一提，[LightLDA](https://github.com/Microsoft/lightlda) Scalable, fast, and lightweight system for large-scale topic modeling 大规模主题模型

```bash
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM
Rscript build_r.R
```
