# 图像处理 {#chap-image-manipulation}

```{r,eval=FALSE}
library(magick)
library(jpeg)
library(png)
library(tiff)
```

```bash
magick cloud.HEIC -resize 10% cloud.png
```

iPhone 12 Pro 拍摄的云图 cloud.HEIC，原始尺寸为 $4032 \times 3024$，这里用 [ImageMagick](https://imagemagick.org/) 将 HEIC 格式转化为 PNG 格式，且尺寸缩小为十分之一。

```{r}
library(png)
```

```{r}
dat = readPNG("images/cloud.png")

format(object.size(dat), units = "Mb", standard = "auto")
```

极小值和极大值点

```{r cloud-contour, fig.width=5.5, fig.height=5, fig.cap="云图的等高线图"}
filled.contour(dat[,,1], color.palette = terrain.colors, axes = FALSE)
```

```{r fig.width=5.5, fig.height=5}
filled.contour(dat[,,2], color.palette = terrain.colors, axes = FALSE)
```


```{r fig.width=5.5, fig.height=5}
filled.contour(dat[,,3], color.palette = terrain.colors, axes = FALSE)
```


```{r fig.width=5.5, fig.height=5}
filled.contour(dat[,,4], color.palette = terrain.colors, axes = FALSE)
```



```{r cloud-persp, fig.width=5.5, fig.height=5, fig.cap="云图的透视图"}
library(shape)
persp(dat[, , 1],
  theta = 0, phi = 90,
  border = "transparent",
  axes = FALSE, box = FALSE,
  col = drapecol(dat[, , 1], col = terrain.colors(100)),
  xlab = "X", ylab = "Y", zlab = "Z"
)
```

