# 交互式数据表格 {#chap:interactive-data-tables}

<!-- 本章不混合介绍 shiny -->

Greg Lin [reactable](https://github.com/glin/reactable) 覆盖测试 99\%  [react-table](https://github.com/tannerlinsley/react-table) 属于 [react](https://github.com/facebook/react) 框架，超棒的 [react 模块合集](https://github.com/enaqx/awesome-react) 也许机智如你，可以引入更多优秀的 react 模块到 R 语言社区。谢益辉开发的 [DT](https://github.com/rstudio/DT) 包覆盖测试 31\% 是基于 [DataTables](https://datatables.net/) 的一个 [jQuery](https://jquery.com/) 框架，Richard Iannone 开发的 [gt](https://github.com/rstudio/gt) 包覆盖测试 78\% 类似 ggplot2，完全基于 R 语言试图打造一个表格的语法，他们都是背靠开源组织和大公司。任坤开发的 [formattable](https://github.com/renkun-ken/formattable) 包覆盖测试 96\%，朱昊开发的 [kableExtra](https://github.com/haozhu233/kableExtra) 大大扩展了 **knitr** 包的 kable 函数的功能，没有覆盖测试，详细文档见  <https://haozhu233.github.io/kableExtra/awesome_table_in_html_cn.html>，他们属于单枪匹马。

```{r,eval=FALSE}
library(reactable) # 主要介绍
library(gt) # 动态
library(kableExtra) # 网页 和 LaTeX 支持
# library(DT) # 动态 与 shiny 包冲突
# library(formattable) # 简单提一下
```




```{r, eval=FALSE}
# ui.R 前端
library(shiny)
shinyUI(fluidPage(
  # 应用的标题名称
  titlePanel("Old Faithful Geyser Data"),
  # 边栏
  fluidRow(
    column(
      12,
      DT::dataTableOutput("table")
    )
  )
))

# server.R 服务端
library(shiny)
shinyServer(function(input, output, session) {
  iris_df <- iris
  colnames(iris_df) <- gsub("\\.", "_", tolower(colnames(iris_df)))
  output$table <- DT::renderDataTable(iris_df,
    options = list(
      pageLength = 5,
      initComplete = I("function(settings, json) {alert('Done.');}")
    ), server = F
  )
})
```
