# 自然语言处理 {#chap:natural-language-processing}

> 这个章节是一个大类的topic涉及很多算法
> 为与其它章节保持一致，这里题目可能应该改为模型或算法的名称， LDA
> 首先介绍潜狄利克雷分配、隐马尔可夫模型等文本挖掘和主题模型 Text Mining and Topic Modeling
> 必读 Probabilistic Latent Semantic Analysis [@Hofmann_1999_PLS] 和 Latent Dirichlet Allocation 诞生的经典文章[@LDA_2003_JMLR] 和经典算法 fast collapsed Gibbs sampler 实现[@LDA_2010_Gibbs] 

[Dmitriy Selivanov](https://dsnotes.com/) 基于 C++ 开发的 [text2vec](https://github.com/dselivanov/text2vec) 在词嵌入、主题建模中具有极高的计算效率

[textmineR](https://github.com/TommyJones/textmineR) 可用于文本挖掘和主题模型，
[topicmodels](https://cran.r-project.org/web/packages/topicmodels/index.html) 包 [@topicmodels_2011_JSS] 基于C/C++实现 Latent Dirichlet Allocation LDA 模型和 Correlated Topics Models (CTM)  [lda](https://cran.r-project.org/web/packages/lda/) 也是基于 C 语言实现 fast collapsed Gibbs sampler 用于 LDA，更多关于文本挖掘的主题包含在自然语言处理的视图内[^nlp-task-view]

通俗的中文读物参看统计之都上范建宁的 [LDA 主题模型简介](https://cosx.org/2010/10/lda-topic-model)、靳志辉的 [LDA-math-LDA 文本建模](https://cosx.org/2013/03/lda-math-lda-text-modeling/) 和 [LDA-math 文本建模](https://cosx.org/2013/03/lda-math-text-modeling/)

Julia Silge 和 David Robinson 的著作 [Text Mining with R: A Tidy Approach](https://www.tidytextmining.com/) 可为文本挖掘和主题模型提供入门介绍，词频

课程 [Text as Data](https://github.com/cbail/textasdata) 涉及基本的文本分析、基于字典的文本分析和主题模型、文本网络、词嵌入的各类算法

[^nlp-task-view]: https://CRAN.R-project.org/view=NaturalLanguageProcessing

## 文本分类 {#Text-Classification}

1. E-Commerce Reviews 数据集

[Shirin Glander](https://shirinsplayground.netlify.com/) Explaining Black-Box Machine Learning Models: Text classification with LIME [博客文章](https://shirinsplayground.netlify.com/2018/07/explaining_ml_models_code_text_lime/)

[Abien Fred Agarap](https://afagarap.me/) Statistical Analysis on E-Commerce Reviews, with Sentiment Classification using Bidirectional Recurrent Neural Network (RNN) 实现 keras 和 sklearn <https://github.com/AFAgarap/ecommerce-reviews-analysis>

