# 非线性模型 {#chap:nonlinear-models}

```{r,include=FALSE}
library(magrittr)
library(ggplot2)
```

> If you give people a linear model function you give them something dangerous.
> 
>   --- John Fox useR! 2004, Vienna (May 2004)

## 压力随温度的变化 {#sec:pressure}

NLM  Nonlinear Models 一元非线性模型`nlm`

```{r}
plot(pressure, xlab = "Temperature (deg C)",
     ylab = "Pressure (mm of Hg)",
     main = "pressure data: Vapor Pressure of Mercury")

plot(pressure, xlab = "Temperature (deg C)",  log = "y",
     ylab = "Pressure (mm of Hg)",
     main = "pressure data: Vapor Pressure of Mercury")
```


## 树的体积和高度随生长的时间变化 {#sec:trees}

- Volume 木材体积，立方英尺
- Height 高度，英尺
- Girth 树的直径，不是“胸围”长，英寸

```{r trees,fig.asp=1}
data(trees, package = "datasets")
library(ggplot2)
library(patchwork)
p1 <- ggplot(data = trees) +
  geom_line(aes(x = Girth, y = Volume), color = "red") +
  theme_minimal()
p2 <- ggplot(data = trees) +
  geom_line(aes(x = Girth, y = Height), color = "blue") +
  theme_minimal()
p3 <- ggplot(data = trees) +
  geom_line(aes(x = Height, y = Volume), color = "green") +
  theme_minimal()
p1 / p2 / p3
```

Dirk Eddelbuettel 开发的 RcppEigen 包提供 fastLm 函数拟合线性模型， [实现细节](https://stackoverflow.com/questions/32137870) 和 `RcppArmadillo::fastLm` 有什么区别

```{r}
# 线性回归
lm_mod <- lm(log(Volume) ~ log(Girth), data = trees)
summary(lm_mod)

# flm_mod1 <- RcppEigen::fastLm(log(Volume) ~ log(Girth), data = trees)
# summary(flm_mod1)
```
