# 面向对象编程 {#chap:object-oriented-programming}

进入这一章的读者都是对编程感兴趣的读者，希望在工程能力上有所提升的读者。那么最重要的是：

> Code should be written to minimize the time it would take for someone else to understand it.
>
> — The Art of Readable Code, Boswell, D. / Foucher, T.

代码可读性，代码复用性，代码维护性，代码扩展性，代码简洁性，代码高效性，代码容错性，我们共勉吧！如果读者已投身商业公司，应当以完成任务为第一，这自不必说！


标准计算和非标准计算 Standard and non-standard evaluation in R https://www.brodieg.com/2020/05/05/on-nse/ 

## 环境 {#environment}

```r
environment(fun = NULL)
environment(fun) <- value

is.environment(x)

.GlobalEnv
globalenv()
.BaseNamespaceEnv

emptyenv()
baseenv()

new.env(hash = TRUE, parent = parent.frame(), size = 29L)

parent.env(env)
parent.env(env) <- value

environmentName(env)

env.profile(env)
```


## 引用 {#quote}


```r
get(x, pos = -1, envir = as.environment(pos), mode = "any",
    inherits = TRUE)

mget(x, envir = as.environment(-1), mode = "any", ifnotfound,
     inherits = FALSE)

dynGet(x, ifnotfound = , minframe = 1L, inherits = FALSE)
```



```r
get Return the Value of a Named Object

exists Is an Object Defined?

exists(x, where = -1, envir = , frame, mode = "any",
       inherits = TRUE)

get0(x, envir = pos.to.env(-1L), mode = "any", inherits = TRUE,
     ifnotfound = NULL)
```


## 调用栈 {#sec:call-stack}

Functions to Access the Function Call Stack

```r
sys.call(which = 0)
sys.frame(which = 0)
sys.nframe()
sys.function(which = 0)
sys.parent(n = 1)

sys.calls()
sys.frames()
sys.parents()
sys.on.exit()
sys.status()
parent.frame(n = 1)

sys.source Parse and Evaluate Expressions from a File
```

## 闭包 {#sec:closure}

An illustration of lexical scoping.

```r
demo(scoping)
```

## 递归 {#recursion}

Using recursion for adaptive integration

```r
demo(recursion)
```

## 异常捕获和处理 {#catching-and-handling-errors}


```r
demo(error.catching)
```

## 判断对象属性 {#is-things}

```r
demo(is.things)
```


## 除虫 {#debug}

[Debugging with RStudio](https://support.rstudio.com/hc/en-us/articles/205612627)

## 性能优化 {#sec:performance}

## 代码质量检测 {#test}

单元测试 testthat、静态代码检查 lintr、覆盖测试 covr、集成测试 Travis-CI

Github Action 工具合集 https://github.com/sdras/awesome-actions

快速参考手册
https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
https://github.com/github/actions-cheat-sheet


创建 R 包的流程 https://mdneuzerling.com/post/data-science-workflows/
