---
title: "R 语言编程指南"
subtitle: "副标题"
date: "`r format(Sys.Date(), '%Y年%m月%d日')`"
author:
- Author One
- Author Two
abstract-title: "摘要"
abstract: |
 | 摘要内容
output: 
  word_document: 
    toc: yes
    number_sections: yes
    #reference_docx: default.docx
bibliography: 
 - packages.bib
biblio-style: plainnat
natbiboptions: "authoryear,round"
subject: 'R Markdown'
category: "动态文档"
keywords: 
 - markdown
 - pandoc
link-citations: yes
colorlinks: yes
toc-title: "目录"
description: |
    This is a long
    description.

    It consists of two paragraphs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R 语言

## 动态文档 {#sec-document}

> A Markdown-formatted document should be publishable as-is, as plain text, without looking like it’s been marked up with tags or formatting instructions.  
> 
> --- John Gruber

这是一份 R Markodwn 文档 [@rmarkdown2018]。 Markdown 提供一种简洁的格式语法，支持数学公式 $\alpha$ 和 $\beta$，用来生成 HTML、PDF 和 MS Word 文档。

当你点击 **Knit** 按钮时，就会生成一份包含正文和代码执行结果的文档。你可以像这样嵌入 R 代码块：

```{r cars}
summary(cars)
```

# 参考文献 {#reference}

```{r bib,include=FALSE,cache=FALSE}
# automatically create a bib database for R packages
bib <- knitr::write_bib(
  x = c(
    .packages(), "knitr", "rmarkdown"
  ), file = NULL, prefix = ""
)
bib <- unlist(bib)
# remove the ugly single quotes required by CRAN policy
bib <- gsub("(\\\n)", " ", bib)
xfun::write_utf8(bib, "packages.bib")
```
