---
title: "Using TikZ"
output: 
  pdf_document: 
    latex_engine: xelatex
    extra_dependencies:
      ctex:
       - fontset=fandol
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(
  citation.bibtex.max = 999,
  tinytex.engine = 'xelatex',
  tikzDefaultEngine = "xetex"
)
```

## TikZ in R Markdown

```{r dk-curve, engine="tikz", out.width="75%", echo=FALSE, fig.align='center', fig.cap="TikZ 绘制邓宁-克鲁格曲线", engine.opts=list(classoption="dvipsnames,tikz", extra.preamble="\\usepackage[fontset=fandol]{ctex}")}
\begin{tikzpicture}[scale=2, transform shape]
\draw[<->, thick] (8,0) node[below]{大师} -- (0,0) node[left]{低} -- (0,7) node[left]{高};
\draw (4,0) node[below]{\textbf{智慧}} -- (0,0) node[below right]{巨婴} -- (0,4.5) node[above left, rotate=90]{\textbf{自信程度}};
\draw (1, 5.5) node[above]{愚昧山峰};
\draw (2, 0.2) node[above]{绝望山谷};
\draw (4.5, 3) node[above, rotate=60]{开悟之旅};
\draw (7, 6) node[above]{持续平稳高原};
\draw (4, -0.5) node[below]{\textbf{（知识\texttt{+}经验）}};
\draw[very thick, ForestGreen] (0,0) to [out=80,in=100] (1,5) 
    to [out=-80,in=100] (1.5, 1) to [out=-80,in=230] (6,5)
    to [out=50,in=190] (8, 6);
\end{tikzpicture}
```

