---
title: "PowerPoint 模板"
author: "黄湘云"
date: "`r format(Sys.time(), tz = 'Asia/Taipei', usetz = TRUE)`"
output: 
  bookdown::powerpoint_presentation2:
    toc: yes
bibliography: 
 - packages.bib
link-citations: yes
colorlinks: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

这是一份 R Markodwn 文档 [@rmarkdown2018] 第\@ref(sec:figure)节介绍如何插入图片。 Markdown 提供一种简洁的格式语法，用来编辑 HTML、PDF 和 MS Word 文档。更多详情见 <http://rmarkdown.rstudio.com>。

当你点击 **Knit** 按钮时，就会生成一份包含正文和代码执行结果的文档。

## 嵌套列表

1. Bullet 1
   1. Bullet 1
   1. Bullet 2
   1. Bullet 3
1. Bullet 2
   - Bullet 1
   - Bullet 2
   - Bullet 3
1. Bullet 3

## R 代码输出

```{r cars, echo = TRUE}
summary(cars)
```

## GGplot2 图形 {#sec:figure}

```{r sleep, echo=FALSE,fig.cap="药物对睡眠时长的影响"}
library(ggplot2)
ggplot(data = sleep, aes(x = group, y = extra, color = group)) +
  geom_boxplot() +
  geom_jitter() +
  theme_minimal(base_size = 16)
```

## 软件信息 {.allowframebreaks}

```{r}
xfun::session_info("rmarkdown", dependencies = FALSE)
```

## 参考文献

```{r bib,include=FALSE,cache=FALSE}
# automatically create a bib database for R packages
bib <- knitr::write_bib(
  x = c(
    .packages(), "knitr", "rmarkdown", "bookdown"
  ), file = NULL, prefix = ""
)
bib <- unlist(bib)
# remove the ugly single quotes required by CRAN policy
bib <- gsub("(\\\n)", " ", bib)
xfun::write_utf8(bib, "packages.bib")
```
